# Generated by Django 5.0.6 on 2024-07-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=20)),
                ('gst', models.CharField(max_length=10)),
            ],
        ),
    ]
